import { Routes } from '@angular/router';
import { canMatchAdmin, canMatchBorrowerSubscription, canMatchDashboard, canMatchMailbox, canMatchMessages, canMatchNewItem, canMatchPartner, canMatchSettings, canMatchSubscription } from './core/guards/route-guards';

export const routes: Routes = [
  { path: '', loadComponent: () => import('./features/home/home.component').then(m => m.HomeComponent) },
  { path: 'connect', loadComponent: () => import('./features/connect/connect.component').then(m => m.ConnectComponent) },
  { path: 'connect/mfa', loadComponent: () => import('./features/connect-mfa/connect-mfa.component').then(m => m.ConnectMfaComponent) },
  { path: 'connect/admin', loadComponent: () => import('./features/connect-admin/connectAdmin').then(m => m.ConnectAdminComponent) },
  { path: 'connect/partner', loadComponent: () => import('./features/connect-partner/connectPartner').then(m => m.ConnectPartnerComponent) },
  { path: 'dashboard', canMatch: [canMatchDashboard], loadComponent: () => import('./features/dashboard/dashboard.component').then(m => m.DashboardComponent) },
  { path: 'dashboard/transaction', canMatch: [canMatchDashboard], loadComponent: () => import('./features/transaction-overview/transaction-overview.component').then(m => m.TransactionOverviewComponent) },
  { path: 'user/preview', canMatch: [canMatchDashboard], loadComponent: () => import('./features/user-preview/user-preview.component').then(m => m.UserPreviewComponent) },
  { path: 'admin', canMatch: [canMatchAdmin], loadComponent: () => import('./features/admin/admin.component').then(m => m.AdminComponent) },
  { path: 'admin/confirm', canMatch: [canMatchAdmin], loadComponent: () => import('./features/admin-action-confirm/admin-action-confirm.component').then(m => m.AdminActionConfirmComponent) },
  { path: 'admin/locations', canMatch: [canMatchAdmin], loadComponent: () => import('./features/location-manager/location-manager.component').then(m => m.LocationManagerComponent) },
  { path: 'partner', canMatch: [canMatchPartner], loadChildren: () => import('./features/partner/partner.routes').then(m => m.PARTNER_ROUTES) },
  { path: 'messages', canMatch: [canMatchMessages], loadComponent: () => import('./features/messages/messages.component').then(m => m.MessagesComponent) },
  { path: 'mailbox/compose', canMatch: [canMatchMailbox], loadComponent: () => import('./features/mailbox-compose/mailbox-compose.component').then(m => m.MailboxComposeComponent) },
  { path: 'mailbox/delete/:id', canMatch: [canMatchMailbox], loadComponent: () => import('./features/mailbox-delete/mailbox-delete.component').then(m => m.MailboxDeleteComponent) },
  { path: 'mailbox', canMatch: [canMatchMailbox], loadComponent: () => import('./features/mailbox/mailbox.component').then(m => m.MailboxComponent) },
  { path: 'listing/:id/delete', loadComponent: () => import('./features/listing-delete/listing-delete.component').then(m => m.ListingDeleteComponent) },
  { path: 'listing/:id/report', loadComponent: () => import('./features/listing-report/listing-report.component').then(m => m.ListingReportComponent) },
  { path: 'listing/:id/profile', loadComponent: () => import('./features/listing-profile/listing-profile.component').then(m => m.ListingProfileComponent) },
  { path: 'listing/:id/review', loadComponent: () => import('./features/listing-review/listing-review.component').then(m => m.ListingReviewComponent) },
  { path: 'listing/:id/return', loadComponent: () => import('./features/listing-return/return').then(m => m.ReturnComponent) },
  { path: 'listing/:id/accept-return', loadComponent: () => import('./features/listing-return/accept-return').then(m => m.AcceptReturnComponent) },
  { path: 'listing/:id/book', loadComponent: () => import('./features/listing-booking/listing-booking.component').then(m => m.ListingBookingComponent) },
  { path: 'listing/:id', loadComponent: () => import('./features/listing-detail/listing-detail.component').then(m => m.ListingDetailComponent) },
  { path: 'new', canMatch: [canMatchNewItem], loadComponent: () => import('./features/new-item/new-item.component').then(m => m.NewItemComponent) },
  { path: 'new-item', canMatch: [canMatchNewItem], loadComponent: () => import('./features/new-item/new-item.component').then(m => m.NewItemComponent) },
  { path: 'new-item/payout-setup', canMatch: [canMatchNewItem], loadComponent: () => import('./features/new-item-payout-setup/new-item-payout-setup.component').then(m => m.NewItemPayoutSetupComponent) },
  { path: 'edit/:id', canMatch: [canMatchNewItem], loadComponent: () => import('./features/new-item/new-item.component').then(m => m.NewItemComponent) },
  { path: 'settings', canMatch: [canMatchSettings], loadComponent: () => import('./features/settings/settings.component').then(m => m.SettingsComponent) },
  { path: 'settings/subscription/cancel', canMatch: [canMatchSettings], data: { action: 'cancel-subscription' }, loadComponent: () => import('./features/settings-action-confirm/settings-action-confirm.component').then(m => m.SettingsActionConfirmComponent) },
  { path: 'settings/security/device/:id/revoke', canMatch: [canMatchSettings], data: { action: 'revoke-device' }, loadComponent: () => import('./features/settings-action-confirm/settings-action-confirm.component').then(m => m.SettingsActionConfirmComponent) },
  { path: 'settings/security/2fa/disable', canMatch: [canMatchSettings], data: { action: 'disable-2fa' }, loadComponent: () => import('./features/settings-action-confirm/settings-action-confirm.component').then(m => m.SettingsActionConfirmComponent) },
  { path: 'settings/account/delete', canMatch: [canMatchSettings], data: { action: 'delete-account' }, loadComponent: () => import('./features/settings-action-confirm/settings-action-confirm.component').then(m => m.SettingsActionConfirmComponent) },
  { path: 'settings/payments/method/:id/remove', canMatch: [canMatchSettings], data: { action: 'remove-payment-method' }, loadComponent: () => import('./features/settings-action-confirm/settings-action-confirm.component').then(m => m.SettingsActionConfirmComponent) },
  { path: 'rate', loadComponent: () => import('./features/rate/rate.component').then(m => m.RateComponent) },
  { path: 'subscription', canMatch: [canMatchSubscription], loadComponent: () => import('./features/subscription/subscription.component').then(m => m.SubscriptionComponent) },
  { path: 'subscription/required', canMatch: [canMatchSubscription], loadComponent: () => import('./features/subscription-required/subscription-required.component').then(m => m.SubscriptionRequiredComponent) },
  { path: 'subscription/confirm', canMatch: [canMatchSubscription], loadComponent: () => import('./features/subscription-confirm/subscription-confirm.component').then(m => m.SubscriptionConfirmComponent) },
  { path: 'subscription/checkout', canMatch: [canMatchSubscription], loadComponent: () => import('./features/subscription-checkout/subscription-checkout.component').then(m => m.SubscriptionCheckoutComponent) },
  { path: 'subscription/upgrade', canMatch: [canMatchSubscription], loadComponent: () => import('./features/subscription-upgrade/subscription-upgrade.component').then(m => m.SubscriptionUpgradeComponent) },
  { path: 'borrower-subscription', canMatch: [canMatchBorrowerSubscription], loadComponent: () => import('./features/borrower-subscription/borrower-subscription.component').then(m => m.BorrowerSubscriptionComponent) },
  { path: 'verification/email', loadComponent: () => import('./features/email-verification/email-verification.component').then(m => m.EmailVerificationComponent) },
  { path: 'terms', loadComponent: () => import('./features/terms/terms.component').then(m => m.TermsComponent) },
  { path: 'privacy', loadComponent: () => import('./features/privacy-policy/privacy-policy.component').then(m => m.PrivacyPolicyComponent) },
  { path: 'cookies', loadComponent: () => import('./features/cookie-notice/cookie-notice.component').then(m => m.CookieNoticeComponent) },
  { path: '**', redirectTo: '' }
];
