version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nearshare-backend
    environment:
      PORT: 8080
      SSL_ENABLED: "false"
      SETTINGS_HTTP_ENABLED: "false"
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      SSL_PASSWORD: ${SSL_PASSWORD}
      KEYSTORE_ACCESS_TOKEN_ALIAS: ${KEYSTORE_ACCESS_TOKEN_ALIAS}
      KEYSTORE_ACCESS_TOKEN_PW: ${KEYSTORE_ACCESS_TOKEN_PW}
      KEYSTORE_REFRESH_TOKEN_ALIAS: ${KEYSTORE_REFRESH_TOKEN_ALIAS}
      KEYSTORE_REFRESH_TOKEN_PW: ${KEYSTORE_REFRESH_TOKEN_PW}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      FRONTEND_BASE_URL: ${FRONTEND_BASE_URL}
      SUBSCRIPTION_PLUS_STRIPE_PRICE_ID: ${SUBSCRIPTION_PLUS_STRIPE_PRICE_ID}
      SUBSCRIPTION_PRO_STRIPE_PRICE_ID: ${SUBSCRIPTION_PRO_STRIPE_PRICE_ID}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      R2_ACCOUNT_ID: ${R2_ACCOUNT_ID}
      R2_ACCESS_KEY_ID: ${R2_ACCESS_KEY_ID}
      R2_SECRET_ACCESS_KEY: ${R2_SECRET_ACCESS_KEY}
      R2_BUCKET_NAME: ${R2_BUCKET_NAME}
      R2_ENDPOINT: ${R2_ENDPOINT}
      R2_PUBLIC_URL: ${R2_PUBLIC_URL}
      STRIPE_PUBLIC_KEY: ${STRIPE_PUBLIC_KEY}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
    ports:
      - "8081:8080"
    networks:
      - nearshare-network
    restart: unless-stopped

networks:
  nearshare-network:
    driver: bridge
