ALTER TABLE listings ADD COLUMN IF NOT EXISTS available_unlimited boolean DEFAULT true;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS available_from timestamp;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS available_to timestamp;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS partner_submitted_at timestamp;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS partner_submitted_by uuid;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS partner_reviewed_at timestamp;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS partner_reviewed_by uuid;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS partner_review_note varchar(500);
ALTER TABLE listings ADD COLUMN IF NOT EXISTS partner_rejection_reason varchar(500);
ALTER TABLE listings ADD COLUMN IF NOT EXISTS partner_borrow_requested_at timestamp;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS partner_borrow_requested_by uuid;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS partner_borrow_reviewed_at timestamp;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS partner_borrow_reviewed_by uuid;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS partner_borrow_rejection_reason varchar(500);
ALTER TABLE users ADD COLUMN IF NOT EXISTS admin_scope varchar(20);
