package com.nearshare.api.model.enums;

public enum AvailabilityStatus {
    AVAILABLE, BORROWED, PENDING, SCHEDULED, BLOCKED, HIDDEN, GIFTED, SOLD, APPROVED, DISPUTED, PARTNER_PENDING_APPROVAL, PARTNER_BORROW_REQUESTED
}
